### ISSUE TITLE
Missing dependency com.vendor.dialogic:gctapi:jar:6.7.1

### ISSUE THREAD

**Issue by arslan70** [RestComm/camelgateway#6]
When trying to build the gateway, the following warning is thrown

[WARNING] The POM for com.vendor.dialogic:gctapi:jar:6.7.1 is missing, no dependency information available

Which fails the build process.

**Comment by nhanth87** [comment]
Please follow step 2 to step 6 for installing gctapi and jxmtool.
https://github.com/RestComm/jss7/wiki/Build-jSS7-from-Source

**Comment by arslan70** [comment]
able to build now by manually installing gctApi.jar from the link. Thank you.

**Comment by nhanth87** [comment]
We have support forum at:
https://groups.google.com/forum/#!forum/mobicents-public
Please use it for further question 

Br,
TN
